### ISSUE TITLE
[3.1.3 on 0.17.25] Does not read blueprints

### ISSUE THREAD

**Issue by N3X15** [Choumiko/FARL#102] opened 2019-04-05 02:10 UTC
FARL does not read blueprints on 0.17.

# Things tried

* Upgrading from 0.17.23 to 0.17.25
* Clicking the Read button.
* Right-clicking the Read button.
* Clicking the Read button with the blueprint. (Click phases through the button and places the blueprint on the terrain, possible raytracing or event-handling error?)

# Environment
## Game
* Factorio 0.17.25 on Windows 10 Pro x64 (Build 17134.648)
* AutoDeconstruct v0.1.12
* Compound Splitters Continued v0.17.1
* Dectorio v0.9.10
* Enhanced Map Colors v1.4.8
* FARL v3.1.3
* Flare Stack v2.2.3
* Flow Control v3.0.4
* Honk v3.0.0
* Logistic Train Network v1.10.5
* OpteraLib v0.1.2
* Squeak Through v1.3.0
* The Fat Controller v4.0.5
* Vehicle Snap v1.17.1
* Angel's Infinite Ores v0.8.3
* Bullet Trails v0.4.1
* Nixie Tubes v0.17.3
* Pushbutton v0.17.0

## Save
https://www.nexisonline.net/downloads/bug-reports/factorio-farl-blueprint-read-issues/virtual_env.7z

SHA256Sum:
```
ccec3ad7b4c7f2247495b32e12d4c7eadb516d767479dff851e963b1d14200b8  virtual_env.7z
```

Included `mods/` so reproduction of the bug isn't a pain. Save is called `0.17`.

## Straight Blueprint
```
0eNqNkWFrgzAQhv/L+zkpGrUb+StjDLWHPYhRknRMJP99UdfSUgf9eMm9zz3czWjMhUbHNkDP4HawHvpjhufO1mZ5C9NI0OBAPQRs3S+Vq9kgCrA90Q90Hj8FyAYOTFt+LaYve+kbcqnhlvQhZbtzkCtCYBx8Sg12GZVIshSYoLMYxRNEPYyXf4rPCHWoNsihSoondtRu3+UOtLhBG+4kmdTruJXjYGgHnf9vV75ml93J7VCqVxelriZp8+tt9N0pBb7J+bX5rcjyY/auykLF+AuXw6KL
```

## Diagonal Blueprint
```
0eNqNkdFuhCAQRf9lnqFB1G7DrzSbRt2JOwmiAWxqDP++iBuzVh/2CQbmnrmZO0OtRxwsGQ9qBmp640B9z+CoNZVe3vw0ICggjx0wMFW3VLYiDYEBmRv+gcrClQEaT55w1adi+jFjV6ONDZvS+aht754nBIOhd1HVm2VUJHHJYFqOCL+RxWb9uwR2YMqdG/50fCRmH+XKjJc9tTyh5hu1ppajjr2WGj70Go9skcAinHCK99zJpznx31t2wizf3WKRmIcdxpBSjOoldQa/aN3akIvsU3zJIpchPAADs7Ce
```

![factorio_2019-04-04_18-37-46](https://user-images.githubusercontent.com/110073/55599614-732c8680-570d-11e9-82f8-d541ce99f12d.jpg)

**Comment by Choumiko** [comment] 2019-04-05 08:13
Thanks for the report
That is most likely a duplicate of https://mods.factorio.com/mod/FARL/discussion/5c8ea765e687c0000b9f25d7
I guess the Clear, Vertical, Horizontal Statistics buttons also don't work.

I reported it as a Factorio bug a while ago here: https://forums.factorio.com/viewtopic.php?f=7&t=67799

You can either use the console commands i added: /farl_read_bp /farl_clear_bp /farl_vertical_bp /farl_diagonal_bp (You need to be in the farl AND have the blueprint on the cursor) or try closing the FatController GUI, this might move it up enough for the buttons to work (The issue appears only when the buttons are in the lower quarter of the screen it seems) and/or try reducing the Interface scale to read the blueprints.
It's a bit awkward at the moment, so i might just move the buttons to the top in one of the next updates.

By the way, including the mods isn't necessary, we can auto download the mods for a save from the load game screen (a fairly small button in the top right, easy to miss ;) )

**Comment by N3X15** [comment] 2019-04-05 18:03
Will do, thanks.

As for the inclusion of the mods, I still was operating under the assumption that the game didn't have that feature implemented yet.

**Closed as completed** 2019-07-04 09:55 UTC
